version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      ENABLE_ROLLING_LOGS: "true"
      LOG_TIMESTAMP: "true"
      MAX_PLAYERS: 10
      DIFFICULTY: "easy"
      USE_AIKAR_FLAGS: "true"
      MEMORY: "4G"
      TZ: "Europe/Amsterdam"
    ports:
      - "25565:25565"
    volumes:
      - "~/minecraft_data:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped
